### ISSUE TITLE
Confusing licensing

### ISSUE THREAD

**Issue by jonassmedegaard** [sass/perl-libsass#11]
Hi,

Issue #6 seemingly was about relicensing this project from Perl-style (a.k.a. "Artistic or GPL-1+") to MIT-style (a.k.a. "Expat").

Several code files, however, still contain either Perl-style licensing or the non-license statement "All Rights Reserved." at the top while having also MIT-style licensing at the bottom.

Reading those files it is unclear if the resulting licensing is "either-or" or "both".

Please consider either a) remove Perl-style licensing statements, or b) clarify if resulting licensing is intended to be "either-or" (a.k.a. dual-licensing) or "both" (which is unusual and it should then probably be carefully worded to distinguish from the Perl-style licensing which itself is a dual-licensing).

In any case, you should consider removing the non-licensing statements as they serve no sensible purpose (they are negated by the licensing, or arguably conflicts with it).

**Comment by mgreter** [comment]
I've added MIT headers to all relevant files!
