### ISSUE TITLE
CSS::Sass-3.3.3 fails to build on MacOS and Linux

### ISSUE THREAD

**Issue by genehack** [sass/perl-libsass#22]
Looks like libsass started using C++11 extensions at some point, and the Makefile.PL isn't injecting the right flags for that. On MacOS X, I get this error:

```
cc -c  -I. -Ilibsass/include -fno-common -DPERL_DARWIN -mmacosx-version-min=10.11 -fno-strict-aliasing -pipe -fstack-protector-strong -I/opt/local/include -Wall -Wextra -Wno-unused-parameter -o libsass/src/ast.o -O3   -DVERSION=\"3.3.3\" -DXS_VERSION=\"3.3.3\"  "-I/opt/plenv/versions/5.24.0/lib/perl5/5.24.0/darwin-2level/CORE"  -D LIBSASS_VERSION=\"3.3.6\" libsass/src/ast.cpp
In file included from libsass/src/ast.cpp:2:
In file included from libsass/src/ast.hpp:35:
libsass/src/units.hpp:24:10: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
    IN = UnitClass::LENGTH,
```

Similar error on Linux, but there it wants the `-std=c++11` flag added instead.

**Comment by mgreter** [comment]
Actually [that should be the case] [1]. Can you debug why this does not happen on your system? Because [build matrix] [2] seems to indicate that it works on "darwin" and I have no mac at hand to test myself.

[1]: https://github.com/sass/perl-libsass/blob/develop/Makefile.PL#L227
[2]: http://matrix.cpantesters.org/?dist=CSS-Sass

**Comment by genehack** [comment]
I can try if you give me some idea of what you need done. FWIW, that's the matrix for an earlier release -- the one for 3.3.3 has a [lot more yellow ](http://matrix.cpantesters.org/?dist=CSS-Sass%203.3.3). Looking at one of the [reported failures](http://www.cpantesters.org/cpan/report/5d62adc6-1538-11e6-a075-a5bb47b29db8), that's exactly what I'm seeing.

**Comment by genehack** [comment]
Also worth noting: I also see this on a Linux system (and the CPAN Testers report I linked above is from a Linux system as well) -- this is _not_ MacOS X specific.

**Comment by mgreter** [comment]
I would start at the line in Makefile.PL I linked above, because I don't see why the flags are not applied. The matrix seems to fluctuate quite a bit since the systems doing these tests seem to come and go. Everything with a gcc below 4.6 is expected to fail, and most (if not all) yellows should be because of that. And I honestly don't know why you also seem to get this on linux ...

**Comment by mgreter** [comment]
Probably the easiest way would be if I could get a remote access to test it myself; if that would be an option for you. Otherwise I cannot do much, since I am not able to reproduce your issue.

**Comment by mgreter** [comment]
> Looking at one of the reported failures, that's exactly what I'm seeing. 

This indicates your compiler is not recent enough to support the c++11 features libsass is using.

**Comment by genehack** [comment]
I just did a PR (#23) with a small tweak to `Makefile.PL` that fixes the issue for me. 

FWIW, the two compilers I'm using here are:

```
% cc --version                                                                                                                                                                                                                                                                                                                                                       fix-build ✗  14:59:00
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

and 

```
% cc --version                                                                                                                                                                                                                                                                                                       fix-build-22 •  14:58:51
cc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mgreter** [comment]
Thanks for your effort! Continuing this in https://github.com/sass/perl-libsass/pull/23 ...
