### ISSUE TITLE
Older Perl version don't install deps automatically

### ISSUE THREAD

**Issue by mgreter** [sass/perl-libsass#29]
Build dependencies like `Cpp::Guess` are correctly referenced in the meta data, but older perl versions (cpan) don't seem to act accordingly. I think there are some options to bundle such deps, but I don't know what the current best practice for CPAN modules is in this regard (http://cpan-prc.org/).

http://www.cpantesters.org/cpan/report/42b15c34-f318-11e6-a7d5-523f3119c05d

**Comment by eserte** [comment]
The 3.4.2 release had broken META files. See https://metacpan.org/source/OCBNET/CSS-Sass-3.4.2/META.yml — every line has a brace at the beginning and the end.

3.4.3 looks better in this regard.

**Comment by mgreter** [comment]
Yep, saw it too. This already happened on 3.3.6 release. But I don't know why as I certainly didn't do this by hand. Will need to keep an eye on it. AFAIR some older versions ignore "build/requires", which is the point of this issue. Embedding Cpp::Guess would solve this ...

**Comment by mgreter** [comment]
Closing this as it seems to be resolved now.
Will try to keep an eye on it so it doesn't happen again!
