### ISSUE TITLE
Latest release 3.4.3 is not indexed

### ISSUE THREAD

**Issue by eserte** [sass/perl-libsass#30]
The CPAN.pm shell and MetaCPAN still show 3.4.2 as the latest release:
```
cpan[1]> m CSS::Sass
Reading '/home/cpansand/.cpan/Metadata'
  Database was generated on Fri, 24 Feb 2017 03:17:02 GMT
Module id = CSS::Sass
    CPAN_USERID  OCBNET (Marcel Greter <cpan@ocb.changeip.net>)
    CPAN_VERSION 3.004002
    CPAN_FILE    O/OC/OCBNET/CSS-Sass-3.4.2.tar.gz
    UPLOAD_DATE  2017-02-15
    INST_FILE    (not installed)
```
https://metacpan.org/release/CSS-Sass → shows 3.4.2

Maybe an indexing problem at PAUSE?

**Comment by mgreter** [comment]
That is strange as http://search.cpan.org/~ocbnet/CSS-Sass/ shows the correct version!?

**Comment by eserte** [comment]
Maybe it's implemented differently there (e.g. using always the latest version, regardless what's in the PAUSE index).

Did you get an error or success mail from PAUSE after your last upload?
Maybe a reindex at PAUSE would fix the problem?

**Comment by mgreter** [comment]
Triggered a reindex and it seems to be correct now! Thanks for the heads up!

http://api.metacpan.org/release/CSS-Sass
