### ISSUE TITLE
(CSS::Sass-3.4.11)Seems hang using cpan install under Strawberry Perl 5.26.0(32bit) on Windows 7. 

### ISSUE THREAD

**Issue by twata1** [sass/perl-libsass#34]
Hi,

When I run `cpan OCBNET/CSS-Sass-3.4.11.tar.gz`, It looks like it hang up like this.

    C:\home\bath>cpan OCBNET/CSS-Sass-3.4.11.tar.gz
    CPAN: CPAN::SQLite loaded ok (v0.211)
    Database was generated on Tue, 06 Feb 2018 12:33:57 GMT
    
    CPAN: Digest::SHA loaded ok (v5.96)
    CPAN: Compress::Zlib loaded ok (v2.074)
    Checksum for C:\Strawberry\cpan\sources\authors\id\O\OC\OCBNET\CSS-Sass-3.4.11.tar.gz ok
    CPAN: Archive::Tar loaded ok (v2.26)
I typed `Ctrl + C`

    Out of memory! 
    Terminate batch job? (Y/N)

[My workaround]
I used `cpanm` instead of `cpan`.

I hope this helps.

**Comment by mgreter** [comment]
Thanks for your report, unfortunately this seems to be an upstream issue in Archive::Tar.
I have created a Pull Request there to speed up the extraction: https://github.com/jib/archive-tar-new/pull/22

Another approach without CPANM would be to extract the tarball manually and call `cpan .`
Interesting that this issue hasn't popped up earlier (will check some older perl versions now).

**Comment by twata1** [comment]
Under Strawberry Perl 5.26.1, it certainly was able to confirm that it can be installed with `cpan .` like this.

    C:\home\bath1\CSS-Sass-3.4.11>cpan .
    You are visiting the local directory
      '.'
      without lock, take care that concurrent processes do not do likewise.
    CPAN: CPAN::SQLite loaded ok (v0.211)
    Database was generated on Tue, 06 Feb 2018 21:48:25 GMT
    
    You are visiting the local directory
      'C:/home/bath1/CSS-Sass-3.4.11/.'
      without lock, take care that concurrent processes do not do likewise.
      C:/home/bath1/CSS-Sass-3.4.11/.
      Has already been unwrapped into directory C:/home/bath1/CSS-Sass-3.4.11/.
    CPAN: CPAN::Meta::Requirements loaded ok (v2.140)
    CPAN: Parse::CPAN::Meta loaded ok (v2.150010)
    CPAN: CPAN::Meta loaded ok (v2.150010)
    CPAN: Module::CoreList loaded ok (v5.20170923)
    Configuring C:/home/bath1/CSS-Sass-3.4.11/. with Makefile.PL
    CPAN: CPAN::Reporter loaded ok (v1.2018)
    Reporting via CPAN::Reporter is disabled for local directories
    Building libsass plugins
    Building shared libsass lib
    Compiling release build
    Detected libsass 3.4.9
    Detected GCC compiler 7.1.0 ...
    Consider installing Win32::ChangeNotify
    Or configure with `--native-watcher` option
    Checking if your kit is complete...
    Looks good
    Installing as a site module
    Generating a gmake-style Makefile
    Writing Makefile for CSS::Sass
    Writing MYMETA.yml and MYMETA.json

(snip)

    All tests successful.
    Files=13, Tests=18408, 50 wallclock secs ( 3.07 usr +  0.27 sys =  3.34 CPU)
    Result: PASS
      C:/home/bath1/CSS-Sass-3.4.11/.
      C:\Strawberry\c\bin\gmake.exe test -- OK
    Running make install

(snip)

Thank you for Another approach information.

**Comment by twata1** [comment]
For now, Archive::Tar 2.30 seems good.

**Comment by mgreter** [comment]
Seems fixed now with new Archive::Tar version!
