### ISSUE TITLE
(CSS-Sass-3.6.0) `make test` failure on MacOS

### ISSUE THREAD

**Issue by genehack** [sass/perl-libsass#41]
First, there are a number of deprecation warnings emitted: 

```
t/10_sass_value_op.t .... 1/40 DEPRECATION WARNING on line 1 of [C-VALUE]:
The operation `#2a2b2c times #2a2b2c` is deprecated and will be an error in future versions.
Consider using Sass's color functions instead.
https://sass-lang.com/documentation/Sass/Script/Functions.html#other_color_functions

DEPRECATION WARNING on line 1 of [C-VALUE]:
The operation `#2a2b2c div #2a2b2c` is deprecated and will be an error in future versions.
Consider using Sass's color functions instead.
https://sass-lang.com/documentation/Sass/Script/Functions.html#other_color_functions

DEPRECATION WARNING on line 1 of [C-VALUE]:
The operation `#2a2b2c plus #2a2b2c` is deprecated and will be an error in future versions.
Consider using Sass's color functions instead.
https://sass-lang.com/documentation/Sass/Script/Functions.html#other_color_functions
...
```

But the bigger issue is that another set of tests just flat fail: 

```
t/10_sass_value_op.t .... ok
t/11_sass_plugins.t ..... Failed 9/9 subtests
t/98_sass_srcmaps.t ..... skipped: Disabled
t/99_sass_specs.t ....... ok

Test Summary Report
-------------------
t/11_sass_plugins.t   (Wstat: 11 Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: Bad plan.  You planned 9 tests but ran 0.
Files=14, Tests=6633,  6 wallclock secs ( 0.33 usr  0.05 sys +  3.84 cusr  1.66 csys =  5.88 CPU)
Result: FAIL
Failed 1/14 test programs. 0/6633 subtests failed.
make: *** [test_dynamic] Error 255
```
This is with `perl-5.30.0`

**Comment by mgreter** [comment]
Hmm, that's sad. Thanks for the report though. Will try to look into it this weekend.
In the meantime you might get it working by calling `perl Makefile.PL --no-plugins`!?
Also the error seems to happen with plugins, so you may just ignore it if you don't use them.

**Comment by mgreter** [comment]
Unfortunately I haven't been able to reproduce it either on my Mac VM nor my [FreeBSD VM][1].
Is there anything special with your perl setup? Could you give some info about your system?
What happens if you ignore the error and go on with the install. Do the plugins still fail?

```
make install
psass --list-plugins
echo "foo { sin: sin(\$PI); }" | psass --math-plugin
```

[1]: http://matrix.cpantesters.org/?dist=CSS-Sass;os=freebsd;perl=5.30.0;reports=1

**Comment by mgreter** [comment]
After a few hours trying to reproduce I give up for now.
It might have something to do with how mac resolves `dylib`.
I probably will just disable plugins for mac as I don't
see how I can get it working properly on that OS 😞

**Comment by mgreter** [comment]
The only thing that seems to give some sort of success is:
`install_name_tool -change blib/arch/auto/CSS/Sass/libsass.dylib libsass.dylib plugins/math/math.dylib`
But I have no idea why we even end up with that dependency on a relative path, as the linker cmd is:
`g++ -Lblib/arch/auto/CSS/Sass -lsass`

**Comment by mgreter** [comment]
If you'd like please try `https://github.com/sass/perl-libsass/tree/build/OSX`:

```bash
git clone https://github.com/sass/perl-libsass --branch build/OSX
cd perl-libsass && perl Makefile.PL && make -j8 test && make install && cd ..
echo "foo { sin: sin(\$PI); }" | psass --math-plugin
```

**Comment by mgreter** [comment]
otool -L perl-libsass/blib/arch/auto/CSS/Sass/plugins/math/math.dylib 
perl-libsass/blib/arch/auto/CSS/Sass/plugins/math/math.dylib:
	math.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	@loader_path/../../libsass.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

**Comment by eserte** [comment]
BTW, I see a similar failure on some of my FreeBSD smokers (various OS versions, from 10 to 13). A sample one:
```
t/11_sass_plugins.t ..... 
Failed 9/9 subtests 
...
Test Summary Report
-------------------
t/11_sass_plugins.t   (Wstat: 138 Tests: 0 Failed: 0)
  Non-zero wait status: 138
  Parse errors: Bad plan.  You planned 9 tests but ran 0.
```
Wstat=138 means a bus error. Sometimes it's also a segmentation fault.

**Comment by genehack** [comment]
Sorry, I had missed the updates on this ticket somehow, but just ran into the same issue when building modules for 5.31.5 and re-discovered the ticket. The [fix](https://github.com/sass/perl-libsass/issues/41#issuecomment-495943263) given above works for me!

**Comment by mgreter** [comment]
No problem, thanks for checking @genehack! By that it works now, do you mean the OSX branch I posted or the `--no-plugin` solution? Thanks for clarification :)

**Comment by genehack** [comment]
@mgreter The OS branch.
