### ISSUE TITLE
ExtUtils::MakeMaker configure_requires version too low

### ISSUE THREAD

**Issue by eserte** [sass/perl-libsass#45]
If EUMM is too old, then the build stops:
```
Output from '/opt/perl-5.24.1/bin/perl Makefile.PL':

Building libsass plugins
Building shared libsass lib
Compiling release build
Detected libsass 3.6.4
Detected GCC compiler (version unknown) ...
Your current ExtUtils::MakeMaker has a bug
You need to upgrade ExtUtils::MakeMaker to 7.20+
```

However, it seems that the version specification for EUMM does not reflect the required version:

```
configure_requires:

    Module              Need Have   
    ------------------- ---- -------
...
    ExtUtils::MakeMaker 6.52 7.10_02
```

**Comment by mgreter** [comment]
Thanks for the report, that seems rather weird.
The following message is meant if your version is between 7.10 and 7.20.
No idea why the check fails on your side, so maybe you could help me with that:

```perl
# Fix an issue with EU::MM > 7.10 as reported in:
# https://github.com/sass/perl-libsass/issues/25
my $EMMV = $ExtUtils::MakeMaker::VERSION;
# Bug has been fixed in version 7.20
if ($EMMV > 7.10 && $EMMV < 7.20) {
	# Fix another issue if as-needed is not supported
	# https://github.com/sass/perl-libsass/issues/26
	unless (`ld --help` =~ /--no-as-needed/) {
		warn "Your current ExtUtils::MakeMaker has a bug\n";
		die "You need to upgrade ExtUtils::MakeMaker to 7.20+\n";
	}
}
```

This is basically the issue you seem to be seeing.
Can you please post the result of the following:

```bash
perl -MExtUtils::MakeMaker -e "print $ExtUtils::MakeMaker::VERSION"
```
You might need to add a backslash before the dollar.

Thank you!

**Comment by mgreter** [comment]
Sorry, should have looked more clearly at your original post 🤦 

So you are actually using version 7.10_02 of MakeMaker. This version indeed has
an issue which was detected correctly 😄 Point is, the issue only exists between
version 7.10 and 7.20, so I didn't bump the mandatory version. Seems that caused
the confusion. I will try to update the message to a bit more specific 😉 

Going to close the therefore and have a nice day!

**Comment by mgreter** [comment]
PR to improve the message is at https://github.com/sass/perl-libsass/pull/46

**Comment by mgreter** [comment]
P.s. I might also bump the required version too.

**Comment by mgreter** [comment]
And btw. thanks for the perl smokers, just made the connection 😄
