### ISSUE TITLE
Some builds fail due to plugin tests (monstyl older FreeBSD)

### ISSUE THREAD

**Issue by mgreter** [sass/perl-libsass#47]
E.g. http://www.cpantesters.org/cpan/report/539c8044-8bc4-11ea-b831-a71e1f24ea8f
Maybe @eserte would have some insight as to what exactly the error message is.
It looks like it could be a segfault or something similar (maybe not finding the libs).

I already had similar experience with MacOS and Windows, but those I think I got
working correctly, albeit it took me some time to understand how to instruct the
libraries (dll, dynlib, so) to look for dependencies in the right place ...

Tried to reproduce by using a freebsd 10.3 osboxes.org virtual image.
It even looks strangely similar to what the failing report is using.

```
root@osboxes:~ # clang -v
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.3
Thread model: posix
Selected GCC installation:
```

But (un)fortunately I got this result:
```
pkg install perl5.24-5.24.4
pushd /usr/local/bin
ln -s perl5.24.4  perl
ln -s cpan5.24.4 cpan
popd
cpan CSS::Sass
t/11_sass_plugins.t ..... ok
t/98_sass_srcmaps.t ..... skipped: Disabled
t/99_sass_specs.t ....... ok
All tests successful.
```

```
Summary of my perl5 (revision 5 version 24 subversion 4) configuration:

  Platform:
    osname=freebsd, osvers=10.4-release-p13, archname=amd64-freebsd-thread-multi
    uname='freebsd 104amd64-quarterly-job-10 10.4-release-p13 freebsd 10.4-release-p13 amd64 '
    config_args='-sde -Dprefix=/usr/local -Dlibperl=libperl.so.5.24.4 -Darchlib=/usr/local/lib/perl5/5.24/mach -Dprivlib=/usr/local/lib/perl5/5.24 -Dman3dir=/usr/local/lib/perl5/5.24/perl/man/man3 -Dman1dir=/usr/local/lib/perl5/5.24/perl/man/man1 -Dsitearch=/usr/local/lib/perl5/site_perl/mach/5.24 -Dsitelib=/usr/local/lib/perl5/site_perl -Dscriptdir=/usr/local/bin -Dsiteman3dir=/usr/local/lib/perl5/site_perl/man/man3 -Dsiteman1dir=/usr/local/lib/perl5/site_perl/man/man1 -Ui_malloc -Ui_iconv -Uinstallusrbinperl -Dusenm=n -Dcc=cc -Duseshrplib -Dinc_version_list=none -Dcf_by=mat -Dcf_email=mat@FreeBSD.org -Dcf_time=Sat Apr 14 11:26:01 UTC 2018 -Alddlflags=-L/wrkdirs/usr/ports/lang/perl5.24/work/perl-5.24.4 -L/usr/local/lib/perl5/5.24/mach/CORE -lperl -Dshrpldflags=$(LDDLFLAGS:N-L/wrkdirs/usr/ports/lang/perl5.24/work/perl-5.24.4:N-L/usr/local/lib/perl5/5.24/mach/CORE:N-lperl) -Wl,-soname,$(LIBPERL:R) -Doptimize=-O2 -pipe  -fstack-protector -fno-strict-aliasing -Ui_gdbm -Dusemultiplicity=y -Duse64bitint -Dusethreads=y -Dusemymalloc=n -Uusedtrace -Dversiononly'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_FORTIFY_SOURCE=2',
    optimize='-O2 -pipe -fstack-protector -fno-strict-aliasing',
    cppflags='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678, doublekind=3
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16, longdblkind=3
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-lpthread -Wl,-E  -fstack-protector -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib /usr/include/clang/3.4.1 /usr/lib
    libs=-lpthread -lm -lcrypt -lutil -lelf
    perllibs=-lpthread -lm -lcrypt -lutil -lelf
    libc=, so=so, useshrplib=true, libperl=libperl.so.5.24.4
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='  -Wl,-R/usr/local/lib/perl5/5.24/mach/CORE'
    cccdlflags='-DPIC -fPIC', lddlflags='-shared  -L/usr/local/lib/perl5/5.24/mach/CORE -lperl -L/usr/local/lib -fstack-protector'


Characteristics of this binary (from libperl):
  Compile-time options: HAS_TIMES MULTIPLICITY PERLIO_LAYERS
                        PERL_COPY_ON_WRITE PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                        PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP
                        PERL_PRESERVE_IVUV USE_64_BIT_ALL USE_64_BIT_INT
                        USE_ITHREADS USE_LARGE_FILES USE_LOCALE
                        USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                        USE_LOCALE_NUMERIC USE_LOCALE_TIME USE_PERLIO
                        USE_PERL_ATOF USE_REENTRANT_API
  Built under freebsd
  @INC:
    /usr/local/lib/perl5/site_perl/mach/5.24
    /usr/local/lib/perl5/site_perl
    /usr/local/lib/perl5/5.24/mach
    /usr/local/lib/perl5/5.24
    .
```

I'm also looking into if I can somehow mark a test-suite optional. I really still want
to get back the reports from the smokers, but I basically consider them an
incubating feature, so great when they work, not too bad if they don't.

**Comment by eserte** [comment]
It also fails on BINGOS' FreeBSD 12 smoker boxes in a similar way, see
* http://matrix.cpantesters.org/?dist=CSS-Sass%203.6.2;os=freebsd;reports=1#sl=2,1 (sorted by os version)
* http://www.cpantesters.org/cpan/report/aa481fec-8da5-11ea-9066-e374b0ba08e8 (a sample fail report)

**Comment by eserte** [comment]
Also it may fail on MacOSX: http://matrix.cpantesters.org/?dist=CSS-Sass%203.6.2;os=darwin;reports=1#sl=4,1 (please disregard the os version here --- of my reports it's all the same box which is running MacOSX Mojave).

**Comment by mgreter** [comment]
http://www.cpantesters.org/cpan/report/aa481fec-8da5-11ea-9066-e374b0ba08e8 is https://github.com/sass/libsass/issues/3094. Still trying to somehow reproduce the failure we see in those builds, but haven't yet had any success.

**Comment by mgreter** [comment]
After a lot of try and error I finally got at least some progress, as I can reproduce these:
http://matrix.cpantesters.org/?dist=CSS-Sass%203.6.2;os=dragonfly;reports=1
With https://app.vagrantup.com/generic/boxes/dragonflybsd5

As anticipated it's a problem with finding dynamic libraries.
The plugins are installed into `blib/arch/auto/CSS/Sass/plugins/xyz/xyz.so` and I hope I got
the EUMM variables correct by now. The main `libsass.so` is at `blib/arch/auto/CSS/Sass/`.
Beside it is also `Sass.so`, the main bindings, so this one can always find `libsass.so`.
Side note: there is a reason I lead it out that way, had all in one directory before ...

Now in order for any `plugin.so` to find the `libsass.so` dependency, we instruct the
linker with `-Wl,-rpath,\$ORIGIN/../..`, as this should make the linker look for the
needed dependency also in that directory. Darwin installs execute `install_name_tool`
to do basically the same. Now I need to find out if this can be fixed for certain BSDs.

Still not 100% sure this is the same issue we see on FreeBSD; maybe or maybe not.
AFAIR on linux plugins also just segfaulted when they couldn't load their dependencies, so
it could be that dragonfly BSD is actually providing an error message here instead 😃 .

But since I can't reproduce the FreeBSD issues, I kinda doubt it will fix both flavours.

@eserte would there be any chance to like get a copy of a failed VM or anything like that.
Would love to investigate, if I could just reproduce this behavior somehow on FreeBSD :-/

**Comment by mgreter** [comment]
So I looks like the culprit for DragonFly BSD was a missing `-z origin` option during linking.
I hope this option doesn't interfere or fail on any other platform 🤞 
I guess I will see if this also fixes the issues we see with FreeBSD.
Also see https://stackoverflow.com/a/6331749/1550314

**Comment by mgreter** [comment]
At least mingw gold linker gives `unrecognized option '-z'` :-/
