### ISSUE TITLE
Unable to install CSS::Sass

### ISSUE THREAD

**Issue by jhthorsen** [sass/perl-libsass#7]
I've tried installing your module without any success.

```
$ cpanm CSS::Sass
--> Working on CSS::Sass
Fetching http://www.cpan.org/authors/id/O/OC/OCBNET/CSS-Sass-v3.1.0.tar.gz ... FAIL
! Download http://www.cpan.org/authors/id/O/OC/OCBNET/CSS-Sass-v3.1.0.tar.gz failed. Retrying ... 
! Download http://www.cpan.org/authors/id/O/OC/OCBNET/CSS-Sass-v3.1.0.tar.gz failed. Retrying ... 
! Download http://www.cpan.org/authors/id/O/OC/OCBNET/CSS-Sass-v3.1.0.tar.gz failed. Retrying ... 
! Failed to download http://www.cpan.org/authors/id/O/OC/OCBNET/CSS-Sass-v3.1.0.tar.gz
! Failed to fetch distribution CSS-Sass-v3.1.0
```

I also tried to pull it directly from github:
```
$ cpanm -v https://github.com/sass/perl-libsass/archive/master.tar.gz 2>&1|grep -v perl-libsass-master
cpanm (App::cpanminus) 1.7022 on perl 5.020001 built for x86_64-linux-thread-multi
Work directory is /work/1422982046.32421
You have make /usr/bin/make
You have LWP 6.08
You have /bin/tar: tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Unpacking master.tar.gz
--> Working on https://github.com/sass/perl-libsass/archive/master.tar.gz
Fetching https://github.com/sass/perl-libsass/archive/master.tar.gz ... OK
Checking if you have Module::Build 0.36 ... Yes (0.4210)
Running Build.PL
Run 'Build manifest' to generate one

WARNING: Possible missing or corrupt 'MANIFEST' file.
Nothing to enter for 'provides' field in metafile.
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'CSS-Sass' version 'v3.1.0'
Checking dependencies from MYMETA.json ...
Checking if you have Test::More 0 ... Yes (1.001014)
Checking if you have ExtUtils::CBuilder 0 ... Yes (0.280217)
Checking if you have File::Slurp 0 ... Yes (9999.19)
Checking if you have File::chdir 0 ... Yes (0.1009)
OK
Building and testing CSS-Sass-v3.1.0 ... Building CSS-Sass
cc -Ilibsass -I/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi/CORE -fPIC -std=c++0x -Wall -DLIBSASS_VERSION="\"[na]\"" -c -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -o libsass/ast.o libsass/ast.cpp
cc: error: libsass/ast.cpp: No such file or directory
cc: fatal error: no input files
compilation terminated.
error building libsass/ast.o from 'libsass/ast.cpp' at /perl-5.20.1/lib/5.20.1/ExtUtils/CBuilder/Base.pm line 175.
! Installing https://github.com/sass/perl-libsass/archive/master.tar.gz failed. See /work/1422982046.32421/build.log for details. Retry with --force to force install it.
FAIL
```

Do you have any ideas on where I fail?

Looks like I'm not the only one:
> CSS-Sass v0.8.0 ( 386 ALLs 200 FAILs 185 PASSes 1 UNKNOWN )

http://www.cpantesters.org/distro/C/CSS-Sass.html?oncpan=1&distmat=1&version=v0.8.0&grade=3

**Comment by mgreter** [comment]
Hey, thanks very much for your report. Looks like I simply forgot to do a new release. I thought I had removed 3.1.0 from cpan, but it seems it only got removed from my pause account and not actually in the cpan repo. I made a dumb mistake with that version, so I probably just have to do another release.

Will now take a look why master did not build!?
Sorry and I hope you will retry once I figured it out!

**Comment by mgreter** [comment]
I'm pretty sure the error with the `master.tar.gz` is due to github not including submodules within the tarballs. If you check out the branch via git and do a `submodule update`, it may probably just work!

**Comment by jhthorsen** [comment]
I'm running the latest Ubuntu, so it should work since travis is successful.

I will try again by cloning the repo.

**Comment by jhthorsen** [comment]
That worked like a charm! :+1: 

Looking forward to a new release. I'm testing out this version to see if it's stable enough to make it a core dependency of my Mojolicious::Plugin::AssetPack module.

**Comment by mgreter** [comment]
Cool! I would suggest to checkout the test suite, which is IMO pretty extensive and is pretty much the base for us to call it stable :) Libsass is (un?)fortunately a pretty fast moving target, so I took the freedom to not release that often, since there don't seem to be too many active perl users.

DISCLAIMER: Some self advertising: If you're looking for a spriting solution, maybe checkout some of my other stuff I released on github, like https://github.com/mgreter/OCBNET-WebSprite. We actually do all of our Asset Management with [perl] [1] at work.

[1]: https://github.com/mgreter/webmerge

**Comment by jhthorsen** [comment]
Sweet! I guess my timing was just the worst, then since I couldn't install CSS::Sass _right now_.

Thanks for the advertisement - I've been considering something like that myself, but now it could be easier to integrate it in AssetPack.

I think the number of active Perl users would go up, if this was always the latest. Maybe you could automate the build process to make a new build, whenever sass gets a new tag?

**Comment by mgreter** [comment]
Unfortunately that would probably fail a lot of releases (like the last one), since sometimes I need to update `Build.pl` to include new dependecies etc. But in general I try to do a release for every libsass release. I guess the more people are using it (and giving feedback like you did), the more time I'm willing to invest to make releases! Otherwise I'm mostly busy hacking in libsass directly these days.

**Comment by jhthorsen** [comment]
That's really cool :+1: Thanks!
